ShoppingCart.UI/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

//sil sonra
using System.Data.Entity;

using ShoppingCart.Domain.Abstract;
using ShoppingCart.Domain.Entities;
using ShoppingCart.UI.Models;

namespace ShoppingCart.UI.Controllers
{
    public class ImageController : Controller
    {
        private IProductImageRepository repository;

        //TODO: Dışarıdan parametre olarak al bunu
        public int PageSize = 10;
        public ImageController(IProductImageRepository productImageRepository)
        {
            this.repository = productImageRepository;
        }


        public FileContentResult GetImage(int productImageID)
        {
            ProductImage productImage = repository.ProductImages.FirstOrDefault(p => p.ProductImageID == productImageID);
            if (productImage != null)
            {
                return File( System.IO.File.ReadAllBytes(HttpContext.Server.MapPath(productImage.ProductImagePath)), productImage.ProductImageMimeType);
            }
            else
            {
                return null;
            }
        }

	}
}

ShoppingCart.UI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ShoppingCart.Domain.Abstract;
using ShoppingCart.Domain.Entities;

namespace ShoppingCart.UI.Controllers
{
    public class NavController : Controller
    {
        private ICategoryRepository repository;
        public const string LanguageSessionKey = "Language";
        public NavController(ICategoryRepository repo)
        {
            repository = repo;
        }

        [ChildActionOnly]
        public PartialViewResult Menu(string categoryLinkText = null)
        {
            ViewBag.SelectedCategory = categoryLinkText;
            //Parent kategorisi olmayan kategorileri dönüyor.
            IEnumerable<Category> categories = repository.Categories.Where(x=>x.Parent == null).Select(x => x);
            return PartialView(categories);
        }

        public RedirectResult ChangeLanguage(string ReturnURL = "",string Language = "tr")
        {
            string language;
            if(Session[LanguageSessionKey] != null)
            language = Session[LanguageSessionKey] as string;

            Session[LanguageSessionKey] = Language;
            return RedirectPermanent(ReturnURL);
        }
	}
}

ShoppingCart.UI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ShoppingCart.Domain.Abstract;
using ShoppingCart.Domain.Entities;
using ShoppingCart.UI.Models;

using ShoppingCart.UI.Helpers;

namespace ShoppingCart.UI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository productRepository;

        public ProductController(IProductRepository productRepository)
        {
            this.productRepository = productRepository;
        }

        public ActionResult Index(string productLinkText)
        {
            int productInventory = 0;
            if(string.IsNullOrWhiteSpace(productLinkText))
            {
                return RedirectToAction("Index", "Home", new{page =1});
            }

            var product = productRepository.Products.Where(x => x.ProductURLText == productLinkText).SingleOrDefault();
            if (product == null)
            {
                return RedirectToAction("Index", "Home", new { page = 1 });
            }
            ProductAttribute firstProductAttribute = product.ProductAttributes.FirstOrDefault();
            if (firstProductAttribute == null)
            {
                productInventory = product.Inventory;
            }
            else
            {
                List<ProductAttributeValue> firstProductAttributeValues = firstProductAttribute.ProductAttributeValues;
                List<ProductAttributeValueTranslation> firstProductAttributeValueTranslations = new List<ProductAttributeValueTranslation>();

                foreach (ProductAttributeValue productAttributeValue in firstProductAttributeValues)
                {
                    firstProductAttributeValueTranslations.Add(productAttributeValue.ProductAttributeValueTranslations
                        .Where(x => x.Language.LanguageCode == CodeHelpers.GetLanguageCode()).First());
                    productInventory += productAttributeValue.Inventory;
                }
                ViewBag.ProductAttributeValueID = new SelectList(firstProductAttributeValueTranslations, "ProductAttributeValueID", "ProductAttributeValueName");
            }
            ViewBag.ProductInventory = productInventory>10 ? 10 : productInventory ;
            return View(product);

            
        }
	}
}

ShoppingCart.UI/Views/Shared/ProductSummary.cshtml
@model ShoppingCart.Domain.Entities.Product

@*<div class="item">*@
<div class="product list-group-item">
    <div class="thumbnail">
        <a href="@Url.Action("Index", "Product", new { productLinkText = Model.ProductURLText })">
            @if (Model.ProductImages.Count > 0)
            {
                <div>
                    <img class="img-responsive"  src="@Url.Action("GetImage", "Image",
                        new {productImageID= Model.ProductImages.OrderByDescending(x=>x.DisplayOrder).First().ProductImageID })" />
                </div>
            }

            <h4>
                @Model.ProductTranslations.Single(x => x.Language.LanguageCode == @Html.GetLanguageCode()).ProductName
            </h4>
            <h6>@Model.ProductTranslations.Single(x => x.Language.LanguageCode == @Html.GetLanguageCode()).ProductDescription</h6>
            @*renders numerical values as currency according to the culture settings that are in effect on your server*@
            @*You can change the culture setting for your server by adding a sectionto the <system.web> node in the Web.config file like this:
            <globalization culture="en-GB" uiCulture="en-GB" />.*@
            <h4>@Model.DiscountedPrice.ToString("c")</h4>
        </a>
    </div>
</div>
    @*</div>*@

ShoppingCart.UI/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Accessories</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/jqueryval")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Accessories", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div class="row">
               <div class="col-md-3 col-lg-3">
                    @Html.Partial("_AccountMenuPartial")
                </div>
                <div class="col-md-9 col-lg-9">
                    @RenderBody()
                </div>
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Accessories</p>
                </footer>
            </div>
    </div>

    
    @Scripts.Render("~/bundles/bootstrap")
    @*@Scripts.Render("~/bundles/masonry")*@
    @RenderSection("scripts", required: false)
</body>
</html>

ShoppingCart.UI/Views/Shared/_AccountMenuPartial.cshtml
<div class="panel panel-primary well">
    <ul class="list-group nav">
        <li class="list-group-item-heading nav-header disabled">
            @Html.RouteLink(Html.GetLanguageCode() == "tr" ? "Adreslerim": "My Addresses" ,
                new
                {
                    controller = "Address",
                    action = "Index"
                })
        </li>
    </ul>
</div>

ShoppingCart.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Accessories</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Accessories", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    
    <div class="container body-content">
        <div class="row">
            <div class="col-md-2 col-lg-2">
                @{ Html.RenderAction("Menu", "Nav"); }
            </div>
            <div class="col-md-10 col-lg-10">
                @RenderBody()
            </div>
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Accessories</p>
            </footer>
         </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*@Scripts.Render("~/bundles/masonry")*@
    @RenderSection("scripts", required: false)
</body>
</html>